/* automatically generated by rust-bindgen 0.70.1 */

pub const GW_ERROR_CODE_OK: GW_ERROR_CODE = 0;
pub const GW_ERROR_CODE_ERROR: GW_ERROR_CODE = 1;
pub type GW_ERROR_CODE = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gw_status_t {
    pub code: GW_ERROR_CODE,
    pub error_msg: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of gw_status_t"][::std::mem::size_of::<gw_status_t>() - 16usize];
    ["Alignment of gw_status_t"][::std::mem::align_of::<gw_status_t>() - 8usize];
    ["Offset of field: gw_status_t::code"][::std::mem::offset_of!(gw_status_t, code) - 0usize];
    ["Offset of field: gw_status_t::error_msg"]
        [::std::mem::offset_of!(gw_status_t, error_msg) - 8usize];
};
